name: C/C++ CI

on:
  push:
    branches: [ "parsing_2" ]
  pull_request:
    branches: [ "parsing_2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t minishell:test .

    - name: Run tests in Docker container
      run: docker run minishell:test
