name: C/C++ CI

on:
  push:
    branches: [ "parsing_2" ]
  pull_request:
    branches: [ "parsing_2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name : test
      run: ./test.sh
